# SPDX-FileCopyrightText: 2025 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

site_name: Kywy Documentation
theme: dracula
site_dir: _site
plugins:
  - macros:
      module_name: docs/macros
