# SPDX-FileCopyrightText: 2025 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

site_name: Kywy Documentation
theme: dracula
site_dir: _site
plugins:
  - macros:
      module_name: docs/macros
  - mkdoxy:
      save-api: .cache/mkdoxy
      projects:
        kywy:
          src-dirs: src
  - gen-files:
      scripts:
        - docs/generate/main.py
nav:
  - index.md
  - Getting Started: getting_started.md
  - Roadmap: roadmap.md
  - API Reference: api_reference.md
