# SPDX-FileCopyrightText: 2025 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

site_name: Kywy Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.footer
    - search.suggest
    - search.hightlight
    - content.code.copy
site_dir: _site
site_url: https://docs.kywy.io
repo_url: https://github.com/KOINSLOT-Inc/kywy
plugins:
  - search
  - meta
  - tags
  - awesome-nav
  - macros:
      module_name: docs/macros
  - mkdoxy:
      save-api: .cache/mkdoxy
      projects:
        kywy:
          src-dirs: src
  - gen-files:
      scripts:
        - docs/generate/main.py
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
extra:
  social:
    - name: Kywy Discord
      link: https://discord.gg/zAYym57Fy6
      icon: fontawesome/brands/discord
