# SPDX-FileCopyrightText: 2025 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

site_name: Kywy Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.footer
    - search.suggest
    - search.hightlight
    - content.code.copy
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

site_dir: _site
site_url: https://docs.kywy.io
repo_url: https://github.com/KOINSLOT-Inc/kywy
plugins:
  - search
  - meta
  - tags
  - awesome-nav
  - macros:
      module_name: docs/macros
  - mkdoxy:
      save-api: .cache/mkdoxy
      projects:
        kywy:
          src-dirs: src
  - gen-files:
      scripts:
        - docs/generate/main.py
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
extra:
  social:
    - name: Kywy Discord
      link: https://discord.gg/zAYym57Fy6
      icon: fontawesome/brands/discord
