# SPDX-FileCopyrightText: 2025 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "Kywy"
SPDX-PackageSupplier = "KOINSLOT, Inc. <contact@kywy.io>"
SPDX-PackageDownloadLocation = "https://koinslotkywy.com"
annotations = []
