# SPDX-FileCopyrightText: 2025 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

nav:
  - index.md
  - 'First Game: Cookie Clicker': cookie_clicker/index.md
  - 'Maze Game: Custom Images & Collision': maze_game.md
  - bouncing_ball/
