# SPDX-FileCopyrightText: 2025 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

nav:
  - index.md
  - 'Bouncing Ball': bouncing_ball/
  - 'Cookie Clicker': cookie_clicker
  - 'Maze Game': maze
