# SPDX-FileCopyrightText: 2025 KOINSLOT, Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

nav:
  - index.md
  - adventure/
  - 'First Game: Cookie Clicker': cookie_clicker/index.md
  - bouncing_ball/
